/*
 *
 * Clock initialization for OMAP4
 *
 * (C) Copyright 2010
 * Texas Instruments, <www.ti.com>
 *
 * Aneesh V <aneesh@ti.com>
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */
#include <common.h>
#include <asm/u-boot.h>
#include <asm/arch/sys_proto.h>
#include <mmc.h>
#include <timestamp_autogenerated.h>
#include <asm/omap_common.h>
#include <asm/arch/mmc_host_def.h>
#include <i2c.h>

/* Define global data structure pointer to it*/
gd_t gdata __attribute__ ((section(".data")));
bd_t bdata __attribute__ ((section(".data")));
gd_t *gd = &gdata;

typedef void (*u_boot_entry_t)(void)__attribute__ ((noreturn));

void board_init_f(ulong dummy)
{
	relocate_code(CONFIG_SYS_SPL_STACK, &gdata, CONFIG_SYS_SPL_TEXT_BASE);
}

inline void hang(void)
{
	puts("### ERROR ### Please RESET the board ###\n");
	for (;;)
		;
}

#ifdef CONFIG_GENERIC_MMC
int board_mmc_init(bd_t *bis)
{
	omap_mmc_init(0);
	omap_mmc_init(1);
	return 0;
}
#endif

static void mmc_load_uboot_raw(struct mmc *mmc, u32 mmc_dev)
{
	u32 u_boot_size_sectors, err;
	u32 *u_boot_size = (u32 *)(CONFIG_SYS_TEXT_BASE +
				(u32) &_u_boot_size - (u32) &_start);

	/* read one sector first to find u-boot size */
	err = mmc->block_dev.block_read(mmc_dev,
			CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_SECTOR, 1,
			(void *)CONFIG_SYS_TEXT_BASE);
	if (err <= 0)
		goto end;

	if (*u_boot_size != 0xDEADBEEF) {
		err = 0xDEADBEEF;
		goto end;
	}

	/* move to the next word that has size */
	u_boot_size++;

	/*
	 * convert size to sectors - round down is fine because we have
	 * already read 1 sector
	 */
	u_boot_size_sectors = *u_boot_size/MMCSD_SECTOR_SIZE;
	debug("spl: u-boot raw sectors - %d\n", u_boot_size_sectors + 1);
	/* read one sector first to find u-boot size */
	err = mmc->block_dev.block_read(mmc_dev,
			CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_SECTOR + 1,
			u_boot_size_sectors,
			(void *)(CONFIG_SYS_TEXT_BASE + MMCSD_SECTOR_SIZE));
end:
	if (err <= 0) {
		printf("spl: mmc blk read err - %d\n", err);
		hang();
	}
}

static void mmc_load_uboot(u32 mmc_dev)
{
	struct mmc *mmc;
	int err;
	u32 boot_mode;

	mmc_initialize(gd->bd);
	mmc = find_mmc_device(mmc_dev);
	if (!mmc) {
		puts("spl: mmc device not found!!\n");
		hang();
	}

	err = mmc_init(mmc);
	if (err) {
		printf("spl: mmc init failed: mmc_dev - %d err - %d\n",
			mmc_dev, err);
		hang();
	}

	boot_mode = omap_boot_mode();
	if (boot_mode == MMCSD_MODE_RAW)
		mmc_load_uboot_raw(mmc, mmc_dev);
	else {
		puts("spl: wrong MMC boot mode\n");
		hang();
	}
}

void board_init_r(gd_t *id, ulong dummy)
{
	u32 boot_device;
	u_boot_entry_t u_boot_entry = (u_boot_entry_t) CONFIG_SYS_TEXT_BASE;

	timer_init();
	i2c_init(CONFIG_SYS_I2C_SPEED, CONFIG_SYS_I2C_SLAVE);
	boot_device = omap_boot_device();
	switch (boot_device) {
	case BOOT_DEVICE_MMC1:
	case BOOT_DEVICE_MMC2:
		mmc_load_uboot(boot_device - BOOT_DEVICE_MMC1);
		break;
	default:
		printf("SPL: Un-supported Boot Device - %d!!!\n", boot_device);
		hang();
		break;
	}

	/*
	 * Jump to u-boot with magic number as input to indicate that it
	 * was loaded by SPL
	 */
	u_boot_entry();
}

void preloader_console_init(void)
{
	gd->bd = &bdata;
	gd->flags |= GD_FLG_RELOC;
	gd->baudrate = CONFIG_BAUDRATE;
	serial_init();		/* serial communications setup */
	printf("\nU-Boot SPL for Texas Instruments OMAP4 (%s - %s)\n",
		U_BOOT_DATE, U_BOOT_TIME);
}
